### PR TITLE
Add AresManga [Ar]

### PR DESCRIPTION
**Pull request by alimohamed1996**
Add new source AresManga [Arabic]

### CODE REVIEW

**Comment by TheNetsky** [comment]
Tested?

**Comment by alimohamed1996** [comment]
Tested on my device working as expected

**Comment by katake3133** [comment]
Can you add teamx ? 
Swat manga
Arabic source ?

**Comment by TheNetsky** [comment]
> Can you add teamx ? Swat manga Arabic source ?

Make proper requests using the Discord,

**Pull request merged**
