### PR TITLE
PianManga: Use toongod homepage format here too

### PR DESCRIPTION
**Pull request by niclimcy**

### CODE REVIEW

**Comment by TheNetsky** [comment]
Why? It works fine?

**Comment by TheNetsky** [comment]
The facts that THEIR trending tab is broken doesn't mean we need to switch it all over to make 4x more requests. ToonGod uses this because they've entirely disabled their Ajax requests.

**Comment by niclimcy** [comment]
> The facts that THEIR trending tab is broken doesn't mean we need to switch it all over to make 4x more requests. ToonGod uses this because they've entirely disabled their Ajax requests.

Thanks for the hint, I guess bibimanga shouldn’t use this either, let me see if its working fine using ajax method

**Comment by TheNetsky** [comment]
> > The facts that THEIR trending tab is broken doesn't mean we need to switch it all over to make 4x more requests. ToonGod uses this because they've entirely disabled their Ajax requests.
> 
> Thanks for the hint, I guess bibimanga shouldn’t use this either, let me see if its working fine using ajax method

I've added it to Bibi, because they've disabled it as well.

**Pull request closed without merging**
