### PR TITLE
New Source: NightScans

### PR DESCRIPTION
**Pull request by seitenca**

### CODE REVIEW

**Comment by seitenca** [comment]
the sections (new titles, top all time, top monthly, top weekly) only have 5 entries, what is better disable it or not?

**Comment by TheNetsky** [comment]
Remove trailing slash from domain, also up to you.

**Comment by TheNetsky** [comment]
I hope you're also properly testing your sources for all functions correct? A generic doesn't mean it works for all, even if it is supposed to.

**Comment by seitenca** [comment]
> I hope you're also properly testing your sources for all functions correct? A generic doesn't mean it works for all, even if it is supposed to.

How do you test it? I try to search a lot of mangas, search by tags / word, test home section, check mangadetails. If I'm missing something or there is a better way for it, say me please since I'm new to this, and I want to learn

**Comment by TheNetsky** [comment]
> > I hope you're also properly testing your sources for all functions correct? A generic doesn't mean it works for all, even if it is supposed to.
> 
> How do you test it? I try to search a lot of mangas, search by tags / word, test home section, check mangadetails. If I'm missing something or there is a better way for it, say me please since I'm new to this, and I want to learn

Nah, that's what I meant, all those things on multiple items to be sure.

**Comment by seitenca** [comment]
Ok last thing before merging, this source have /manga & /series working, but /series is promoted. Which is better?

**Comment by TheNetsky** [comment]
> Ok last thing before merging, this source have /manga & /series working, but /series is promoted. Which is better?

The one that is most common.

**Comment by seitenca** [comment]
> > Ok last thing before merging, this source have /manga & /series working, but /series is promoted. Which is better?
> 
> The one that is most common.

The default you mean? if so, you can merge whenever you want

**Pull request merged**
