### PR TITLE
Madara

### PR DESCRIPTION
**Pull request by beingsuz**
Just made it simpler & cleaner 

small follow up of #8

don't merge yet thank you

### CODE REVIEW

**Comment by TheNetsky** [comment]
So..?

**Comment by beingsuz** [comment]
Gona try something this weekend did not have time to since I work Night Shift

**Comment by beingsuz** [comment]
after some test its seems to work.

Tested with ManhuaPlus,MadaraDex,AstraScans.
Gona resolve my issues with the TS error then try to make it typesafe

**Comment by TheNetsky** [comment]
Try testing on some foreign sources as well

After that increment the Madara base version number.

**Comment by beingsuz** [comment]
Tested NeoxScans, Manga3asq, AzoraWorld ,ComicKiba all seems to work.

DragonTea is fix no longer does as the video you send on discord.

**Comment by TheNetsky** [comment]
I'll check that out later
Edit: works fine for me

**Comment by TheNetsky** [comment]
Completed?

**Comment by beingsuz** [comment]
Yes

**Comment by beingsuz** [comment]
Being using those change on my device with no problem

**Comment by TheNetsky** [comment]
Inc base version

**Pull request merged**
