### PR TITLE
Buddycomplex Chapter Regex Hell

### PR DESCRIPTION
**Pull request by niclimcy**
Imagine having weird chapters like afterword and chapter 0

### CODE REVIEW

**Comment by TheNetsky** [comment]
Tested?

**Comment by niclimcy** [comment]
> Tested?

Works fine but I am not sure if it is worth the extra complexity to first search for ‘chapter-‘ and falling back to original method if it fails

**Comment by niclimcy** [comment]
IMG_7661
Hmm sorting index seems inconsistent again, i’ll need to look at this later

**Comment by niclimcy** [comment]
I cannot replicate this anymore, seems like source inconsistent labelling/relabelling is at fault and not my changes

**Comment by TheNetsky** [comment]
> I cannot replicate this anymore, seems like source inconsistent labelling/relabelling is at fault and not my changes

So what's the plan with this PR? Did it fix it or does it not matter since it's borked regardless?

**Comment by niclimcy** [comment]
> > I cannot replicate this anymore, seems like source inconsistent labelling/relabelling is at fault and not my changes
> 
> So what's the plan with this PR? Did it fix it or does it not matter since it's borked regardless?

It makes chapter labelling more consistent on certain mangas where they include season numbers in the url.

**Comment by TheNetsky** [comment]
> > > I cannot replicate this anymore, seems like source inconsistent labelling/relabelling is at fault and not my changes
> > 
> > 
> > So what's the plan with this PR? Did it fix it or does it not matter since it's borked regardless?
> 
> It makes chapter labelling more consistent on certain mangas where they include season numbers in the url.

Nice, but are you sure that  didn't go at the cost of other manga?

**Comment by niclimcy** [comment]
It falls back to the old regex when it doesn’t find “chapter”

**Pull request merged**
