### PR TITLE
New Source: EnryuManga

### PR DESCRIPTION
**Pull request by EmZedH**

### CODE REVIEW

**Comment by TheNetsky** [comment]
Tested all features?

**Comment by EmZedH** [comment]
yes, just need to add author and artist selectors

**Comment by EmZedH** [comment]
The author and artist selectors for this site are not included in the parseMangaDetails()

Can i make changes to this function in the MangaStreamParser class to include this sites selectors, or, should i make my own implementation of getMangaDetails() within EnryuManga.ts

**Comment by TheNetsky** [comment]
Try if 
const author = $(`span:contains(${source.manga_selector_author}), .fmed b:contains(${source.manga_selector_author})+span, .imptdt:contains(${source.manga_selector_author}) i, td:contains(${source.manga_selector_author})`).contents().remove().last().text().trim() // Language dependant

const artist = $(`span:contains(${source.manga_selector_artist}), .fmed b:contains(${source.manga_selector_artist})+span, .imptdt:contains(${source.manga_selector_artist}) i, td:contains(${source.manga_selector_artist})`).contents().remove().last().text().trim() // Language dependant

Works within the parser, without breaking the other sources.

**Comment by TheNetsky** [comment]
If it does, you can change to that within MangaStreamParser.

**Comment by EmZedH** [comment]
nope doesnt seems to work

**Comment by TheNetsky** [comment]
Here you go

**Comment by TheNetsky** [comment]
Also your covers aren't loading for Project Updates and Last Updates.

**Comment by EmZedH** [comment]
> Here you go

Tried it in my code...wasn't working
Is it working for u?

**Comment by TheNetsky** [comment]
> > Here you go
> 
> Tried it in my code...wasn't working Is it working for u?

New one I posted works, see commit, also make sure to NOT open a manga that you've already opened because it's cached.

**Comment by EmZedH** [comment]
> Also your covers aren't loading for Project Updates and Last Updates.

Seems to be a fault on the website due to its slow loading

Tried constant refreshing...it eventually loads the images

**Comment by TheNetsky** [comment]
> > Also your covers aren't loading for Project Updates and Last Updates.
> 
> Seems to be a fault on the website due to its slow loading
> 
> Tried constant refreshing...it eventually loads the images

You sure? View more loads them fast, the homepage does not.

**Comment by EmZedH** [comment]
> > > Also your covers aren't loading for Project Updates and Last Updates.
> 
> > 
> 
> > Seems to be a fault on the website due to its slow loading
> 
> > 
> 
> > Tried constant refreshing...it eventually loads the images
> 
> 
> 
> You sure? View more loads them fast, the homepage does not.

Yes sometimes deleting and reinstalling extension or refreshing only worked...there was no issue with image selectors as I checked

**Comment by TheNetsky** [comment]
> > > > Also your covers aren't loading for Project Updates and Last Updates.
> > 
> > 
> > > 
> > 
> > 
> > > Seems to be a fault on the website due to its slow loading
> > 
> > 
> > > 
> > 
> > 
> > > Tried constant refreshing...it eventually loads the images
> > 
> > 
> > You sure? View more loads them fast, the homepage does not.
> 
> Yes sometimes deleting and reinstalling extension or refreshing only worked...there was no issue with image selectors as I checked

Can you share an image?

**Comment by EmZedH** [comment]
photo1
photo2

**Comment by TheNetsky** [comment]
Good enough then.

**Pull request merged**
