### PR TITLE
Add chapter protector plugin bypass, fix source MangaCultivator and add source MahuaSY

### PR DESCRIPTION
**Pull request by Ivanmatthew**
Previously, Madara sources that implemented [this Madara plugin](https://mangabooth.com/product/wp-manga-chapter-protector/), would prevent chapter pages/content from being parsed.
This is now fixed and is made configurable to apply the plugin bypass to new sources.

As a result, MangaCultivator is fixed, and additionally, ManhuaSY is added and proven to be working with the plugin bypass enabled.

### CODE REVIEW

**Comment by Ivanmatthew** [comment]
@TheNetsky I'm going to version the Madara base code, should this be considered major or minor version update?

**Comment by TheNetsky** [comment]
> @TheNetsky I'm going to version the Madara base code, should this be considered major or minor version update?

You can leave as is, I'll change it later, gonna add some other sources later anyways.

**Comment by Ivanmatthew** [comment]
Will it not mess up auto updating sources if I won’t atleast change the version?

**Comment by TheNetsky** [comment]
Then it just won't auto-update unless they do so manually, so no big deal.

**Pull request merged**
